<div class="violet-content">
  <div>
    To access product data and persist orders back into your Magento store Violet requires an API User for Violet use only.
  </div>
  <div>
    <form id="form-manage-apiuser" action="<?php echo $block->escapeUrl($block->getAction()) ?>" method="POST">
      <input name="form_key" type="hidden" value="<?php /* @escapeNotVerified */ echo $block->getFormKey() ?>" />
      <?php if (!$block->integrationExists()) : ?>
      <button id="violet-submit-btn" class="action-default scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" type="submit">
        <span class="ui-button-text">
          <span>Create API Credentials</span>
        </span>
      </button>
      <?php else : ?>

      <?php
        $token = $block->getToken();
      ?>
      <div>
        <div class="fieldset-wrapper-title">
          <strong class="title">
            <span>API Credentials</span>
          </strong>
        </div>
        <div>
          <div class="violet-credential-row">
            <div>
              <label for="api-token">
                API Token
              </label>
            </div>
            <input id="api-token" class="admin__control-text violet-api-credential" type="text" name="api-token" readonly="readonly" value="<?php echo $block->escapeHtml($token->getToken()); ?>" />
          </div>
          <div class="violet-credential-row">
            <div>
              <label for="api-secret">
                API Secret
              </label>
            </div>
            <input class="admin__control-text violet-api-credential" type="text" name="api-secret" readonly="readonly" value="<?php echo $block->escapeHtml($token->getSecret()); ?>" />
          </div>
        </div>
      </div>
      
      <div class="violet-api-credentials-refresh">
        <div class="violet-refresh-notice"><span>Notice</span>: Refreshing your API credentials will break your connection to Violet until you provide the new credentials to Violet.<div>
        <div class="violet-refresh-notice-input"><input type="checkbox" id="accept-refresh-clause" /> <span>I Understand</span></div>
        <button disabled="disabled" id="violet-submit-btn" class="action-default scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" type="submit">
          <span class="ui-button-text">
            <span>Refresh API Credentials</span>
          </span>
        </button>
      </div>
      <?php endif; ?>
    </form>
  </div>
</div>
<style>
    div.violet-content > div {
        margin-bottom: 15px;
    }
    div.violet-credential-row {
      margin-top: 12px;
    }
    input.violet-api-credential {
      width: 400px;
      color: #888;
    }
    div.violet-api-credentials-refresh {
      border-top: 1px solid #ccc;
      margin-top: 50px;
      padding-top: 20px;
    }
    div.violet-refresh-notice  span {
      font-weight: bold;
    }
    div.violet-refresh-notice-input {
      margin: 10px 0;
    }
    div.violet-refresh-notice-input input {
      cursor: pointer;
    }
    div.violet-refresh-notice-input span {
      font-size: 12px;
      line-height: 2px;
      position: relative;
      top: -2px;
      left: 3px;
    }

</style>
<script>
require([
    "jquery"
], function($){
  $('#accept-refresh-clause').on('change', function() {
    if($(this).prop('checked')) {
      $('#violet-submit-btn').prop('disabled', false);
    } else {
      $('#violet-submit-btn').prop('disabled', true);
    }
  });

  $('#form-manage-apiuser').submit(function(e){
      $('#violet-submit-btn').prop('disabled', true);
      $('#violet-submit-btn span span').text('Processing...');
      e.preventDefault();
      $.ajax({
          url: e.originalEvent.srcElement.action,
          type:'post'
      }).done(function(m) {
          location.reload();
      });
  });
});
</script>
